# -*- mode: yaml -*-

jobs:
- job: linux
  pool:
    vmImage: ubuntu-16.04
  container:
      image: pdal/ubuntu-dependencies:latest
      options: --privileged
  timeoutInMinutes: 360
  steps:
  - script: |
      ./autogen.sh
      CXXFLAGS="-std=c++11" ./configure
    displayName: 'configure'
  - script: |
      make
    displayName: 'Build'
  - script: |
      pushd test/geometry/test1
      ./run
      popd

      pushd test/rtree/test1
      ./run
      popd
      pushd test/rtree/test2
      ./run
      popd
      pushd test/rtree/test3
      ./run
      popd
      pushd test/rtree/test4
      ./run
      popd

      pushd test/tprtree/test1
      ./run
      popd
      pushd test/tprtree/test2
      ./run
      popd

      pushd test/mvrtree/test1
      ./run
      popd
      pushd test/mvrtree/test2
      ./run
      popd
    displayName: 'Test'
