# -*- mode: yaml -*-

jobs:
- job: osx
  pool:
    vmImage: macOS-10.15
  timeoutInMinutes: 360
  steps:
  - script: |
      cmake . -DBUILD_TESTING=ON -DCMAKE_VERBOSE_MAKEFILE=ON
    displayName: 'CMake'
  - script: |
      make
    displayName: 'Build'
  - script: |
      make test
    displayName: 'Test'
  - script: |
      make dist
    displayName: 'Dist'
