
jobs:
- job: win

  pool:
    vmImage: vs2017-win2016
  timeoutInMinutes: 360
  steps:
    - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
      displayName: Add conda to PATH

    - script: |
        ECHO ON
        call conda create --yes --quiet --name libspatialindex
      displayName: Create conda environment

    - script: |
        ECHO ON
        call activate libspatialindex
        call conda config --set always_yes True --set show_channel_urls True
        call conda install --yes --quiet --name libspatialindex -c conda-forge ninja cmake -y
      displayName: Install CMake and Ninja
    - script: |
        ECHO ON
        call activate libspatialindex
        call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
        echo %PATH%
        set CC=cl.exe
        set CXX=cl.exe
        mkdir build
        pushd build
        cmake -G "Ninja" ^
            -DCMAKE_BUILD_TYPE=RelWithDebInfo ^
            -DCMAKE_LIBRARY_PATH:FILEPATH="%CONDA_PREFIX%/Library/lib" ^
            -DCMAKE_INCLUDE_PATH:FILEPATH="%CONDA_PREFIX%/Library/include" ^
            -DBUILD_SHARED_LIBS=ON ^
            -DBUILD_TESTING=ON ^
            -DCMAKE_INSTALL_PREFIX="%TEMP%\sidx" ^
            -Dgtest_force_shared_crt=ON ^
        ..
      displayName: 'CMake'
    - script: |
        call activate libspatialindex
        pushd build
        call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
        echo %PATH%
        set CC=cl.exe
        set CXX=cl.exe
        ninja -v
      displayName: 'Build'
    - script: |
        ECHO ON
        call activate libspatialindex
        pushd build
        call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
        set PYTHONHOME="C:/Miniconda/"
        set PYTHONLIB="C:/Miniconda/Lib"
        echo %PYTHONHOME%
        echo %PYTHONLIB%
        ctest -VV --output-on-failure
      displayName: 'Test'
    - script: |
        ECHO ON
        call activate libspatialindex
        pushd build
        call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
        ninja dist
        ninja install
      displayName: 'Dist and install'
    - script: |
        ECHO ON
        call activate libspatialindex
        call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
        call test\postinstall\test_cmake.bat %TEMP%\sidx
      displayName: 'Post-install test'
