pr:
  branches:
    include:
    - master

variables:
  - name: BUILD_TYPE
    value: Release

jobs:
  - template: ./scripts/azp/linux.yml
  - template: ./scripts/azp/win.yml
  - template: ./scripts/azp/osx.yml
  - template: ./scripts/azp/docs.yml
