#! /bin/bash

echo Generating dataset
../Generator 1000 > d
awk '{if ($2 != 2) print $0}' < d > data
awk '{if ($2 == 2) print $0}' < d > queries
rm -rf d

echo Creating new MVR-Tree
../MVRTreeLoad data tree 20 intersection

echo Querying MVR-Tree
../MVRTreeQuery queries tree intersection > res
cat data queries > .t

echo Running exhaustive search
../Exhaustive .t intersection > res2

echo Comparing results
sort -n res > a
sort -n res2 > b
if diff a b
then
echo "Same results with exhaustive search. Everything seems fine."
echo Results: `wc -l a`
rm -rf a b res res2 .t tree.*
else
echo "PROBLEM! We got different results from exhaustive search!"
fi
