Document: libspatialindex1
Title: Debian libspatialindex1 Manual
Author: <insert document author here>
Abstract: This manual describes what libspatialindex1 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libspatialindex1/libspatialindex1.sgml.gz

Format: postscript
Files: /usr/share/doc/libspatialindex1/libspatialindex1.ps.gz

Format: text
Files: /usr/share/doc/libspatialindex1/libspatialindex1.text.gz

Format: HTML
Index: /usr/share/doc/libspatialindex1/html/index.html
Files: /usr/share/doc/libspatialindex1/html/*.html

  
